# Generated by Django 5.1.3 on 2024-11-15 07:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the repository', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the repository')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the repository was uploaded')),
                ('zip_file', models.FileField(help_text='Upload the repository folder as a zip file', upload_to='repositories/')),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
            },
        ),
        migrations.AlterField(
            model_name='adminpic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adminpic', to=settings.AUTH_USER_MODEL),
        ),
    ]
