# Generated by Django 5.1.1 on 2024-11-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InitiativeName', models.CharField(max_length=255)),
                ('FoundationYear', models.IntegerField()),
                ('InitiativeType', models.CharField(max_length=255)),
                ('InitiativeOrigin', models.CharField(max_length=255)),
                ('FocusofAria', models.CharField(max_length=255)),
                ('OfficialLink', models.URLField(max_length=255)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
