# Generated by Django 5.1.3 on 2024-11-15 07:11

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_repository_alter_adminpic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='zip_file',
            field=models.FileField(help_text='Upload the repository folder as a zip file', upload_to='repositories/', validators=[App.models.validate_zip_file]),
        ),
    ]
