# Generated by Django 5.1.1 on 2024-11-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_initiativesmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiativesmodel',
            old_name='FocusofAria',
            new_name='AriaofFocus',
        ),
    ]
