# Generated by Django 5.1.1 on 2024-11-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_repository_alter_adminpic_user'),
        ('App', '0004_rename_ariaoffocus_initiativesmodel_ariaoffocus'),
    ]

    operations = [
    ]
