# Generated by Django 5.1.1 on 2024-11-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_repositorygroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repositorygroup',
            options={'ordering': ['-id']},
        ),
    ]
