# Generated by Django 5.1.1 on 2024-11-25 17:44

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_merge_20241123_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repository',
        ),
        migrations.AlterField(
            model_name='repositoryitem',
            name='file',
            field=models.FileField(upload_to='repositories_items/', validators=[App.models.validate_file_type]),
        ),
    ]
