# Generated by Django 5.1.1 on 2024-11-26 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_delete_repository_alter_repositoryitem_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleTitle', models.CharField(max_length=255)),
                ('ArticleContent', models.TextField()),
                ('DatePublished', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
