# Generated by Django 5.1.3 on 2025-03-24 08:23

import froala_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpic',
            options={'verbose_name_plural': 'Admin Pictures'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Blog Articles'},
        ),
        migrations.AlterModelOptions(
            name='initiativesmodel',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Initiatives & Organizations'},
        ),
        migrations.AlterModelOptions(
            name='repositorygroup',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Repository Groups'},
        ),
        migrations.AlterModelOptions(
            name='repositoryitem',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Respository Datasets'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='ArticleContent',
        ),
        migrations.AddField(
            model_name='blog',
            name='article_type',
            field=models.CharField(choices=[('article', 'Article'), ('journal', 'Journal'), ('special_issue', 'Special Issue')], default='article', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=froala_editor.fields.FroalaField(default='C'),
            preserve_default=False,
        ),
    ]
