# Generated by Django 5.1.3 on 2025-03-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_adminpic_options_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article_type',
            field=models.CharField(choices=[('articles', 'Articles'), ('journals', 'Journals'), ('special_issues', 'Special Issues')], default='article', max_length=20),
        ),
    ]
