# Generated by Django 5.1.3 on 2025-03-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativesmodel',
            name='FoundationYear',
            field=models.DateField(),
        ),
    ]
