# Generated by Django 5.1.3 on 2025-03-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_initiativesmodel_foundationyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativesmodel',
            name='OfficialLink',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
