# Generated by Django 5.1.3 on 2025-04-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_initiativesmodel_officiallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativesmodel',
            name='InitiativeOrigin',
            field=models.CharField(choices=[('Ethiopia (Outside of Tigray)', 'Ethiopia (Outside of Tigray)'), ('Africa', 'Africa'), ('North America', 'North America'), ('Central/South America', 'Central/South America'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('Middle East', 'Middle East'), ('Australia', 'Australia')], max_length=255),
        ),
    ]
