# Generated by Django 5.1.3 on 2025-04-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_initiativesmodel_initiativeorigin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativesmodel',
            name='AriaOfFocus',
            field=models.TextField(),
        ),
    ]
