# Generated by Django 5.1.3 on 2025-05-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_initiativesmodel_ariaoffocus'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativesmodel',
            name='InitiativeTypeforgraph',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
