# Generated by Django 5.1.3 on 2025-07-24 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_initiativesmodel_initiativetypeforgraph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repositorygroup',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Parent Folder'},
        ),
        migrations.AlterField(
            model_name='repositorygroup',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a brief description of the repository group (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='repositorygroup',
            name='name',
            field=models.CharField(help_text='Enter a unique name for the repository group.', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='SubFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a unique name for the sub-folder.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Provide a brief description of the sub-folder (optional).', null=True)),
                ('parent', models.ForeignKey(help_text='Select the parent folder for this sub-folder.', on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='App.repositorygroup')),
            ],
            options={
                'verbose_name_plural': 'Sub Folders',
                'ordering': ['-id'],
            },
        ),
    ]
