# Generated by Django 5.1.3 on 2025-07-24 08:31

import App.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_repositorygroup_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositoryitem',
            name='repository',
        ),
        migrations.AddField(
            model_name='repositoryitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='repositoryitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repositoryitem',
            name='file',
            field=models.FileField(upload_to='repository_items/', validators=[App.models.validate_file_type]),
        ),
    ]
