# Generated by Django 5.1.3 on 2025-08-01 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_remove_repositoryitem_repository_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repositoryitem',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Datasets'},
        ),
        migrations.AlterField(
            model_name='subfolder',
            name='parent',
            field=models.ForeignKey(help_text='Select the parent folder (Repository Group) that this sub-folder belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='App.repositorygroup'),
        ),
    ]
