# Generated by Django 5.1.3 on 2025-08-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_repositoryitem_options_alter_subfolder_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repositoryitem',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Dataset Items'},
        ),
        migrations.CreateModel(
            name='DownloadCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times this file has been downloaded.')),
                ('first_downloaded_at', models.DateTimeField(blank=True, help_text='Timestamp of the first download.', null=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent download.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository_item', models.OneToOneField(help_text='The repository item being tracked for downloads.', on_delete=django.db.models.deletion.CASCADE, related_name='download_counter', to='App.repositoryitem')),
            ],
            options={
                'verbose_name_plural': 'Download Counters',
                'ordering': ['-download_count', '-last_downloaded_at'],
            },
        ),
    ]
