# Generated by Django 5.1.3 on 2025-08-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_blog_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id'], 'verbose_name_plural': 'TDR Journals'},
        ),
        migrations.DeleteModel(
            name='AdminPic',
        ),
    ]
