# Generated by Django 5.1.3 on 2025-08-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_blog_options_delete_adminpic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repositorygroup',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Repository'},
        ),
        migrations.AlterModelOptions(
            name='repositoryitem',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Repository Datasets'},
        ),
        migrations.AlterModelOptions(
            name='subfolder',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Repository Folders'},
        ),
        migrations.RemoveField(
            model_name='repositoryitem',
            name='title',
        ),
    ]
