# Generated by Django 5.1.3 on 2025-08-06 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_alter_repositorygroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repositoryitem',
            options={'ordering': ['id'], 'verbose_name_plural': 'Repository Datasets'},
        ),
        migrations.CreateModel(
            name='ViewCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this file has been viewed.')),
                ('first_viewed_at', models.DateTimeField(blank=True, help_text='Timestamp of the first view.', null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent view.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository_item', models.OneToOneField(help_text='The repository item being tracked for views.', on_delete=django.db.models.deletion.CASCADE, related_name='view_counter', to='App.repositoryitem')),
            ],
            options={
                'verbose_name_plural': 'View Counters',
                'ordering': ['-view_count', '-last_viewed_at'],
            },
        ),
    ]
